# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.28.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.28.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/challr535/dev/c/server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/challr535/dev/c/server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.28.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.28.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/challr535/dev/c/server/CMakeFiles /Users/challr535/dev/c/server//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/challr535/dev/c/server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_server

# Build rule for target.
test_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_server
.PHONY : test_server

# fast build rule for target.
test_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/build
.PHONY : test_server/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/soh/soh/Enhancements/custom-message/CustomMessageManager.o: src/soh/soh/Enhancements/custom-message/CustomMessageManager.cpp.o
.PHONY : src/soh/soh/Enhancements/custom-message/CustomMessageManager.o

# target to build an object file
src/soh/soh/Enhancements/custom-message/CustomMessageManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src/soh/soh/Enhancements/custom-message/CustomMessageManager.cpp.o
.PHONY : src/soh/soh/Enhancements/custom-message/CustomMessageManager.cpp.o

src/soh/soh/Enhancements/custom-message/CustomMessageManager.i: src/soh/soh/Enhancements/custom-message/CustomMessageManager.cpp.i
.PHONY : src/soh/soh/Enhancements/custom-message/CustomMessageManager.i

# target to preprocess a source file
src/soh/soh/Enhancements/custom-message/CustomMessageManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src/soh/soh/Enhancements/custom-message/CustomMessageManager.cpp.i
.PHONY : src/soh/soh/Enhancements/custom-message/CustomMessageManager.cpp.i

src/soh/soh/Enhancements/custom-message/CustomMessageManager.s: src/soh/soh/Enhancements/custom-message/CustomMessageManager.cpp.s
.PHONY : src/soh/soh/Enhancements/custom-message/CustomMessageManager.s

# target to generate assembly for a file
src/soh/soh/Enhancements/custom-message/CustomMessageManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src/soh/soh/Enhancements/custom-message/CustomMessageManager.cpp.s
.PHONY : src/soh/soh/Enhancements/custom-message/CustomMessageManager.cpp.s

src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.o: src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.cpp.o
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.o

# target to build an object file
src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.cpp.o
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.cpp.o

src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.i: src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.cpp.i
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.i

# target to preprocess a source file
src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.cpp.i
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.cpp.i

src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.s: src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.cpp.s
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.s

# target to generate assembly for a file
src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.cpp.s
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.cpp.s

src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.o: src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.cpp.o
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.o

# target to build an object file
src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.cpp.o
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.cpp.o

src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.i: src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.cpp.i
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.i

# target to preprocess a source file
src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.cpp.i
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.cpp.i

src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.s: src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.cpp.s
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.s

# target to generate assembly for a file
src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.cpp.s
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.cpp.s

src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.o: src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.cpp.o
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.o

# target to build an object file
src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.cpp.o
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.cpp.o

src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.i: src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.cpp.i
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.i

# target to preprocess a source file
src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.cpp.i
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.cpp.i

src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.s: src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.cpp.s
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.s

# target to generate assembly for a file
src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_server.dir/build.make CMakeFiles/test_server.dir/src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.cpp.s
.PHONY : src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_server"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/soh/soh/Enhancements/custom-message/CustomMessageManager.o"
	@echo "... src/soh/soh/Enhancements/custom-message/CustomMessageManager.i"
	@echo "... src/soh/soh/Enhancements/custom-message/CustomMessageManager.s"
	@echo "... src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.o"
	@echo "... src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.i"
	@echo "... src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_dungeon.s"
	@echo "... src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.o"
	@echo "... src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.i"
	@echo "... src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_exclude_overworld.s"
	@echo "... src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.o"
	@echo "... src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.i"
	@echo "... src/soh/soh/Enhancements/randomizer/3drando/hint_list/hint_list_item.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

